# Generated by Django 3.0.5 on 2020-06-20 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20200620_2241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='userLikes',
        ),
    ]
