# Generated by Django 3.0.5 on 2020-06-20 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_remove_post_userlikes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlikepost',
            name='status',
        ),
    ]
