# Generated by Django 3.0.5 on 2020-06-21 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_auto_20200621_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercommentpost',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
