# Generated by Django 3.0.5 on 2020-06-22 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_postsearch'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='search_value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='PostSearch',
        ),
    ]
