# Generated by Django 3.0.5 on 2020-06-24 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_auto_20200622_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='name_film',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
