# Generated by Django 3.0.5 on 2020-06-24 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_auto_20200624_1327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercommentpost',
            old_name='parentId',
            new_name='parent_id',
        ),
    ]
