# Generated by Django 3.0.5 on 2020-06-24 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0015_auto_20200624_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercommentpost',
            name='parent_id',
            field=models.CharField(blank=True, editable=False, max_length=36, null=True),
        ),
    ]
